---
- name: "ansible handler"
  hosts: redhat
  tasks:
  - name: "installing"
    dnf:
      name: httpd
      state: present
    notify: start httpd

  - name: "configure httpd"
    copy:
       src: ./index.html
       dest: /var/www/html/index.html
    notify: restart httpd
   
  handlers:
  - name: start httpd
    service:
          name: httpd
          state: started

  - name: restart httpd
    service:
          name: httpd
          state: restarted
