---
- name: "Ansible Condition Check"
  hosts: all
  tasks:
  - name: "Update all Redhat Machines"
    dnf:
      update_cache: yes
    when: ansible_os_family == "RedHat"
  - name: "Update all Ubuntu Machines"
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
